### PR TITLE
Support new Intel GPU-enabled compilers

### PR DESCRIPTION
**Pull request by naromero77**

### CODE REVIEW

**Comment by rljacob** [comment]
Another issue:  for Autoconf, you're supposed to editing configure.ac and then generate a new configure file, not edit configure directly.

**Comment by naromero77** [comment]
You have a number of compiler hacks in place already in configure:
https://github.com/MCSclimate/mpi-serial/blob/master/configure#L3364-L3386

How are those generated by autoconf? There is no configure.ac in there, just configure.in.

**Comment by rljacob** [comment]
According to some googling, configure.in is the older version of configure.ac.  autoconf will process both.

I've had to spin back up on this for https://github.com/MCSclimate/MCT/issues/63 so could take care of the MCT changes.

**Comment by naromero77** [comment]
Just to make sure I am following. 

Are you going to add some fixes into configure.ac and I should wait on those? then I can try to add the new Intel compiler work around to the new configure.ac or configure.in?

**Comment by rljacob** [comment]
Yes I'm going to add some things to the MCT configure.ac and could try the ifx ones as well (if I remember how to log in to iris).   You can try modifying the configure.in in mpi-serial in the meantime.

**Comment by naromero77** [comment]
At the moment, these changes are not blocking me from making progress.  I am also under the gun due to some other deadlines. If its alright with you, I can wait until you add your additions to MCT configure.ac.

**Comment by rljacob** [comment]
Replaced by #16

**Pull request closed without merging**
